/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Resume {
  'id' : string,
  'title' : string,
  'jsonData' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'template' : { 'creative' : null } |
    { 'minimal' : null } |
    { 'modern' : null },
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'status' : { 'active' : null } |
    { 'cancelled' : null } |
    { 'inactive' : null },
  'stripeSubscriptionId' : [] | [string],
  'plan' : { 'pro' : null } |
    { 'lite' : null } |
    { 'plus' : null },
  'lastUpdated' : Time,
  'billingCycle' : { 'monthly' : null } |
    { 'yearly' : null },
  'stripeCustomerId' : [] | [string],
  'startDate' : Time,
}
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'failed' : null },
  'paymentMethod' : { 'stripe' : null } |
    { 'paypal' : null },
  'createdAt' : Time,
  'plan' : { 'pro' : null } |
    { 'lite' : null } |
    { 'plus' : null },
  'amountCents' : bigint,
  'updatedAt' : Time,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'displayName' : string,
  'subscription' : [] | [Subscription],
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkStripeSubscription' : ActorMethod<[string], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createResume' : ActorMethod<[Resume], string>,
  'deleteResume' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getResumes' : ActorMethod<[], Array<Resume>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserIdNameMap' : ActorMethod<[], Array<[Principal, string]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getUserTransactions' : ActorMethod<[], Array<Transaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateResume' : ActorMethod<[Resume], undefined>,
  'updateSubscription' : ActorMethod<[Subscription], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];