/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'paymentMethod' : IDL.Variant({ 'stripe' : IDL.Null, 'paypal' : IDL.Null }),
  'createdAt' : Time,
  'plan' : IDL.Variant({
    'pro' : IDL.Null,
    'lite' : IDL.Null,
    'plus' : IDL.Null,
  }),
  'amountCents' : IDL.Nat,
  'updatedAt' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Resume = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'jsonData' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'template' : IDL.Variant({
    'creative' : IDL.Null,
    'minimal' : IDL.Null,
    'modern' : IDL.Null,
  }),
});
export const Subscription = IDL.Record({
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'inactive' : IDL.Null,
  }),
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'plan' : IDL.Variant({
    'pro' : IDL.Null,
    'lite' : IDL.Null,
    'plus' : IDL.Null,
  }),
  'lastUpdated' : Time,
  'billingCycle' : IDL.Variant({ 'monthly' : IDL.Null, 'yearly' : IDL.Null }),
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'startDate' : Time,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'subscription' : IDL.Opt(Subscription),
  'email' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkStripeSubscription' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createResume' : IDL.Func([Resume], [IDL.Text], []),
  'deleteResume' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserIdNameMap' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getUserTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateResume' : IDL.Func([Resume], [], []),
  'updateSubscription' : IDL.Func([Subscription], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'paymentMethod' : IDL.Variant({ 'stripe' : IDL.Null, 'paypal' : IDL.Null }),
    'createdAt' : Time,
    'plan' : IDL.Variant({
      'pro' : IDL.Null,
      'lite' : IDL.Null,
      'plus' : IDL.Null,
    }),
    'amountCents' : IDL.Nat,
    'updatedAt' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Resume = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'jsonData' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'template' : IDL.Variant({
      'creative' : IDL.Null,
      'minimal' : IDL.Null,
      'modern' : IDL.Null,
    }),
  });
  const Subscription = IDL.Record({
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'cancelled' : IDL.Null,
      'inactive' : IDL.Null,
    }),
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'plan' : IDL.Variant({
      'pro' : IDL.Null,
      'lite' : IDL.Null,
      'plus' : IDL.Null,
    }),
    'lastUpdated' : Time,
    'billingCycle' : IDL.Variant({ 'monthly' : IDL.Null, 'yearly' : IDL.Null }),
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'subscription' : IDL.Opt(Subscription),
    'email' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkStripeSubscription' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createResume' : IDL.Func([Resume], [IDL.Text], []),
    'deleteResume' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserIdNameMap' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getUserTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateResume' : IDL.Func([Resume], [], []),
    'updateSubscription' : IDL.Func([Subscription], [], []),
  });
};

export const init = ({ IDL }) => { return []; };