/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Subscription {
    status: Variant_active_cancelled_inactive;
    stripeSubscriptionId?: string;
    plan: Variant_pro_lite_plus;
    lastUpdated: Time;
    billingCycle: Variant_monthly_yearly;
    stripeCustomerId?: string;
    startDate: Time;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Resume {
    id: string;
    title: string;
    jsonData: string;
    createdAt: Time;
    updatedAt: Time;
    template: Variant_creative_minimal_modern;
}
export interface UserProfile {
    displayName: string;
    subscription?: Subscription;
    email: string;
}
export interface Transaction {
    id: string;
    status: Variant_pending_completed_failed;
    paymentMethod: Variant_stripe_paypal;
    createdAt: Time;
    plan: Variant_pro_lite_plus;
    amountCents: bigint;
    updatedAt: Time;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_cancelled_inactive {
    active = "active",
    cancelled = "cancelled",
    inactive = "inactive"
}
export enum Variant_creative_minimal_modern {
    creative = "creative",
    minimal = "minimal",
    modern = "modern"
}
export enum Variant_monthly_yearly {
    monthly = "monthly",
    yearly = "yearly"
}
export enum Variant_pending_completed_failed {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum Variant_pro_lite_plus {
    pro = "pro",
    lite = "lite",
    plus = "plus"
}
export enum Variant_stripe_paypal {
    stripe = "stripe",
    paypal = "paypal"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTransaction(transaction: Transaction): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkStripeSubscription(subscriptionId: string): Promise<string>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createResume(resume: Resume): Promise<string>;
    deleteResume(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getResumes(): Promise<Array<Resume>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserIdNameMap(): Promise<Array<[Principal, string]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSubscription(): Promise<Subscription | null>;
    getUserTransactions(): Promise<Array<Transaction>>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateResume(resume: Resume): Promise<void>;
    updateSubscription(subscription: Subscription): Promise<void>;
}
import type { Resume as _Resume, StripeSessionStatus as _StripeSessionStatus, Subscription as _Subscription, Time as _Time, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTransaction(arg0: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_Transaction_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_Transaction_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkStripeSubscription(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.checkStripeSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkStripeSubscription(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createResume(arg0: Resume): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createResume(to_candid_Resume_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResume(to_candid_Resume_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteResume(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResume(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResumes(): Promise<Array<Resume>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumes();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumes();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserIdNameMap(): Promise<Array<[Principal, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserIdNameMap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserIdNameMap();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSubscription(): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSubscription();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSubscription();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTransactions();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTransactions();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateResume(arg0: Resume): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResume(to_candid_Resume_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResume(to_candid_Resume_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSubscription(arg0: Subscription): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscription(to_candid_Subscription_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscription(to_candid_Subscription_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Resume_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resume): Resume {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    subscription: [] | [_Subscription];
    email: string;
}): {
    displayName: string;
    subscription?: Subscription;
    email: string;
} {
    return {
        displayName: value.displayName,
        subscription: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.subscription)),
        email: value.email
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        active: null;
    } | {
        cancelled: null;
    } | {
        inactive: null;
    };
    stripeSubscriptionId: [] | [string];
    plan: {
        pro: null;
    } | {
        lite: null;
    } | {
        plus: null;
    };
    lastUpdated: _Time;
    billingCycle: {
        monthly: null;
    } | {
        yearly: null;
    };
    stripeCustomerId: [] | [string];
    startDate: _Time;
}): {
    status: Variant_active_cancelled_inactive;
    stripeSubscriptionId?: string;
    plan: Variant_pro_lite_plus;
    lastUpdated: Time;
    billingCycle: Variant_monthly_yearly;
    stripeCustomerId?: string;
    startDate: Time;
} {
    return {
        status: from_candid_variant_n17(_uploadFile, _downloadFile, value.status),
        stripeSubscriptionId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.stripeSubscriptionId)),
        plan: from_candid_variant_n19(_uploadFile, _downloadFile, value.plan),
        lastUpdated: value.lastUpdated,
        billingCycle: from_candid_variant_n20(_uploadFile, _downloadFile, value.billingCycle),
        stripeCustomerId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.stripeCustomerId)),
        startDate: value.startDate
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    jsonData: string;
    createdAt: _Time;
    updatedAt: _Time;
    template: {
        creative: null;
    } | {
        minimal: null;
    } | {
        modern: null;
    };
}): {
    id: string;
    title: string;
    jsonData: string;
    createdAt: Time;
    updatedAt: Time;
    template: Variant_creative_minimal_modern;
} {
    return {
        id: value.id,
        title: value.title,
        jsonData: value.jsonData,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        template: from_candid_variant_n26(_uploadFile, _downloadFile, value.template)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        failed: null;
    };
    paymentMethod: {
        stripe: null;
    } | {
        paypal: null;
    };
    createdAt: _Time;
    plan: {
        pro: null;
    } | {
        lite: null;
    } | {
        plus: null;
    };
    amountCents: bigint;
    updatedAt: _Time;
}): {
    id: string;
    status: Variant_pending_completed_failed;
    paymentMethod: Variant_stripe_paypal;
    createdAt: Time;
    plan: Variant_pro_lite_plus;
    amountCents: bigint;
    updatedAt: Time;
} {
    return {
        id: value.id,
        status: from_candid_variant_n33(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_variant_n34(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        plan: from_candid_variant_n19(_uploadFile, _downloadFile, value.plan),
        amountCents: value.amountCents,
        updatedAt: value.updatedAt
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    inactive: null;
}): Variant_active_cancelled_inactive {
    return "active" in value ? Variant_active_cancelled_inactive.active : "cancelled" in value ? Variant_active_cancelled_inactive.cancelled : "inactive" in value ? Variant_active_cancelled_inactive.inactive : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    lite: null;
} | {
    plus: null;
}): Variant_pro_lite_plus {
    return "pro" in value ? Variant_pro_lite_plus.pro : "lite" in value ? Variant_pro_lite_plus.lite : "plus" in value ? Variant_pro_lite_plus.plus : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    yearly: null;
}): Variant_monthly_yearly {
    return "monthly" in value ? Variant_monthly_yearly.monthly : "yearly" in value ? Variant_monthly_yearly.yearly : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creative: null;
} | {
    minimal: null;
} | {
    modern: null;
}): Variant_creative_minimal_modern {
    return "creative" in value ? Variant_creative_minimal_modern.creative : "minimal" in value ? Variant_creative_minimal_modern.minimal : "modern" in value ? Variant_creative_minimal_modern.modern : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n29(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): Variant_pending_completed_failed {
    return "pending" in value ? Variant_pending_completed_failed.pending : "completed" in value ? Variant_pending_completed_failed.completed : "failed" in value ? Variant_pending_completed_failed.failed : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stripe: null;
} | {
    paypal: null;
}): Variant_stripe_paypal {
    return "stripe" in value ? Variant_stripe_paypal.stripe : "paypal" in value ? Variant_stripe_paypal.paypal : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resume>): Array<Resume> {
    return value.map((x)=>from_candid_Resume_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n31(_uploadFile, _downloadFile, x));
}
function to_candid_Resume_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Resume): _Resume {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Subscription_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subscription): _Subscription {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_pending_completed_failed;
    paymentMethod: Variant_stripe_paypal;
    createdAt: Time;
    plan: Variant_pro_lite_plus;
    amountCents: bigint;
    updatedAt: Time;
}): {
    id: string;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        failed: null;
    };
    paymentMethod: {
        stripe: null;
    } | {
        paypal: null;
    };
    createdAt: _Time;
    plan: {
        pro: null;
    } | {
        lite: null;
    } | {
        plus: null;
    };
    amountCents: bigint;
    updatedAt: _Time;
} {
    return {
        id: value.id,
        status: to_candid_variant_n3(_uploadFile, _downloadFile, value.status),
        paymentMethod: to_candid_variant_n4(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        plan: to_candid_variant_n5(_uploadFile, _downloadFile, value.plan),
        amountCents: value.amountCents,
        updatedAt: value.updatedAt
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    subscription?: Subscription;
    email: string;
}): {
    displayName: string;
    subscription: [] | [_Subscription];
    email: string;
} {
    return {
        displayName: value.displayName,
        subscription: value.subscription ? candid_some(to_candid_Subscription_n37(_uploadFile, _downloadFile, value.subscription)) : candid_none(),
        email: value.email
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Variant_active_cancelled_inactive;
    stripeSubscriptionId?: string;
    plan: Variant_pro_lite_plus;
    lastUpdated: Time;
    billingCycle: Variant_monthly_yearly;
    stripeCustomerId?: string;
    startDate: Time;
}): {
    status: {
        active: null;
    } | {
        cancelled: null;
    } | {
        inactive: null;
    };
    stripeSubscriptionId: [] | [string];
    plan: {
        pro: null;
    } | {
        lite: null;
    } | {
        plus: null;
    };
    lastUpdated: _Time;
    billingCycle: {
        monthly: null;
    } | {
        yearly: null;
    };
    stripeCustomerId: [] | [string];
    startDate: _Time;
} {
    return {
        status: to_candid_variant_n39(_uploadFile, _downloadFile, value.status),
        stripeSubscriptionId: value.stripeSubscriptionId ? candid_some(value.stripeSubscriptionId) : candid_none(),
        plan: to_candid_variant_n5(_uploadFile, _downloadFile, value.plan),
        lastUpdated: value.lastUpdated,
        billingCycle: to_candid_variant_n40(_uploadFile, _downloadFile, value.billingCycle),
        stripeCustomerId: value.stripeCustomerId ? candid_some(value.stripeCustomerId) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    jsonData: string;
    createdAt: Time;
    updatedAt: Time;
    template: Variant_creative_minimal_modern;
}): {
    id: string;
    title: string;
    jsonData: string;
    createdAt: _Time;
    updatedAt: _Time;
    template: {
        creative: null;
    } | {
        minimal: null;
    } | {
        modern: null;
    };
} {
    return {
        id: value.id,
        title: value.title,
        jsonData: value.jsonData,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        template: to_candid_variant_n10(_uploadFile, _downloadFile, value.template)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_creative_minimal_modern): {
    creative: null;
} | {
    minimal: null;
} | {
    modern: null;
} {
    return value == Variant_creative_minimal_modern.creative ? {
        creative: null
    } : value == Variant_creative_minimal_modern.minimal ? {
        minimal: null
    } : value == Variant_creative_minimal_modern.modern ? {
        modern: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_failed): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == Variant_pending_completed_failed.pending ? {
        pending: null
    } : value == Variant_pending_completed_failed.completed ? {
        completed: null
    } : value == Variant_pending_completed_failed.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_cancelled_inactive): {
    active: null;
} | {
    cancelled: null;
} | {
    inactive: null;
} {
    return value == Variant_active_cancelled_inactive.active ? {
        active: null
    } : value == Variant_active_cancelled_inactive.cancelled ? {
        cancelled: null
    } : value == Variant_active_cancelled_inactive.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_stripe_paypal): {
    stripe: null;
} | {
    paypal: null;
} {
    return value == Variant_stripe_paypal.stripe ? {
        stripe: null
    } : value == Variant_stripe_paypal.paypal ? {
        paypal: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_monthly_yearly): {
    monthly: null;
} | {
    yearly: null;
} {
    return value == Variant_monthly_yearly.monthly ? {
        monthly: null
    } : value == Variant_monthly_yearly.yearly ? {
        yearly: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pro_lite_plus): {
    pro: null;
} | {
    lite: null;
} | {
    plus: null;
} {
    return value == Variant_pro_lite_plus.pro ? {
        pro: null
    } : value == Variant_pro_lite_plus.lite ? {
        lite: null
    } : value == Variant_pro_lite_plus.plus ? {
        plus: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
